config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">
  <!-- <header class="header">Bootstrap</header> -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">EventKeeper</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarForm" aria-controls="navbarForm" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarForm">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="#">ホーム <span class="sr-only">(現位置)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">リンク1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">リンク2</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0 ml-auto">
        <input class="form-control mr-sm-2" type="text" placeholder="検索..." aria-label="検索...">
        <button type="submit" class="btn btn-outline-success my-2 my-sm-0">検索</button>
      </form>
    </div>
  </nav>
  <article>
      <div class="contents">
        <!-- カード -->
        <div class="row">
          <div class="col-sm-6 col-md-3">
            <div class="card img-thumbnail">
              <img class="card-img-top" src="https://www.homepage-tukurikata.com/image/lion.jpg" alt="画像">
              <div class="card-body px-2 py-3">
                <h5 class="card-title">タイトル</h5>
                <p class="card-text">コンテンツ コンテンツ コンテンツ コンテンツ</p>
                <p class="mb-0"><a href="#" class="btn btn-primary btn-sm">ボタン</a> <a href="#" class="btn btn-secondary btn-sm">ボタン</a></p>

              </div><!-- /.card-body -->
            </div><!-- /.card -->
          </div><!-- /.col-sm-6.col-md-3 -->
          <div class="col-sm-6 col-md-3">
            <div class="card img-thumbnail">
              <img class="card-img-top" src="https://www.homepage-tukurikata.com/image/lion.jpg" alt="画像">
              <div class="card-body px-2 py-3">
                <h5 class="card-title">タイトル</h5>
                <p class="card-text">コンテンツ コンテンツ コンテンツ コンテンツ</p>
                <p class="mb-0"><a href="#" class="btn btn-primary btn-sm">ボタン</a> <a href="#" class="btn btn-secondary btn-sm">ボタン</a></p>

              </div><!-- /.card-body -->
            </div><!-- /.card -->
          </div><!-- /.col-sm-6.col-md-3 -->
          <div class="col-sm-6 col-md-3">
            <div class="card img-thumbnail">
              <img class="card-img-top" src="https://www.homepage-tukurikata.com/image/lion.jpg" alt="画像">
              <div class="card-body px-2 py-3">
                <h5 class="card-title">タイトル</h5>
                <p class="card-text">コンテンツ コンテンツ コンテンツ コンテンツ</p>
                <p class="mb-0"><a href="#" class="btn btn-primary btn-sm">ボタン</a> <a href="#" class="btn btn-secondary btn-sm">ボタン</a></p>

              </div><!-- /.card-body -->
            </div><!-- /.card -->
          </div><!-- /.col-sm-6.col-md-3 -->
          <div class="col-sm-6 col-md-3">
            <div class="card img-thumbnail">
              <img class="card-img-top" src="https://www.homepage-tukurikata.com/image/lion.jpg" alt="画像">
              <div class="card-body px-2 py-3">
                <h5 class="card-title">タイトル</h5>
                <p class="card-text">コンテンツ コンテンツ コンテンツ コンテンツ</p>
                <p class="mb-0"><a href="#" class="btn btn-primary btn-sm">ボタン</a> <a href="#" class="btn btn-secondary btn-sm">ボタン</a></p>

              </div><!-- /.card-body -->
            </div><!-- /.card -->
          </div><!-- /.col-sm-6.col-md-3 -->
        </div><!-- /.row -->

          <ul class="row">
              <li>contents1</li>
              <li>contents2</li>
              <li>contents3</li>
              <li>contents4</li>
          </ul>
      </div>
      <div class="topic">
           <ul>
              <li>bootstrapを使ってレスポンシブデザインを実現しよう！</li>
              <li>やればできる！bootstrapを使ってみよう！</li>
              <li>怖くない！レスポンシブデザインができるようになればWebアプリケーションもワンランク上に！</li>
          </ul>
      </div>
  </article>
</div>
<!--  -->

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>


  </body>
</html>